export const skillSwap = [
  [
    {
      inputs: [{ internalType: "address", name: "_USDT", type: "address" }],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "uint256",
          name: "id",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "address",
          name: "offerer",
          type: "address",
        },
      ],
      name: "SkillExchangeAccepted",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "uint256",
          name: "id",
          type: "uint256",
        },
      ],
      name: "SkillExchangeCompleted",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "uint256",
          name: "id",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "address",
          name: "requester",
          type: "address",
        },
        {
          indexed: false,
          internalType: "string",
          name: "skillOffered",
          type: "string",
        },
        {
          indexed: false,
          internalType: "string",
          name: "skillRequested",
          type: "string",
        },
      ],
      name: "SkillExchangePosted",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "user",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "reputation",
          type: "uint256",
        },
      ],
      name: "UserRated",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "userAddress",
          type: "address",
        },
        {
          indexed: false,
          internalType: "string",
          name: "userName",
          type: "string",
        },
      ],
      name: "UserRegistered",
      type: "event",
    },
    {
      inputs: [],
      name: "USDT",
      outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
      name: "acceptSkillExchange",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
      name: "completeSkillExchange",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "exchangeCounter",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "_skillOffered", type: "string" },
        { internalType: "string", name: "_skillRequested", type: "string" },
        { internalType: "uint256", name: "_amountForSkill", type: "uint256" },
      ],
      name: "postSkillExchange",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_id", type: "uint256" },
        { internalType: "uint256", name: "_rating", type: "uint256" },
      ],
      name: "rateUser",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "string", name: "_userName", type: "string" }],
      name: "registerUser",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "skillExchanges",
      outputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "address", name: "requester", type: "address" },
        { internalType: "string", name: "skillOffered", type: "string" },
        { internalType: "string", name: "skillRequested", type: "string" },
        { internalType: "uint256", name: "offererReputation", type: "uint256" },
        { internalType: "address", name: "offerer", type: "address" },
        { internalType: "bool", name: "isCompleted", type: "bool" },
        {
          internalType: "uint256",
          name: "ratingFromRequester",
          type: "uint256",
        },
        { internalType: "uint256", name: "ratingFromOfferer", type: "uint256" },
        { internalType: "uint256", name: "amountForSkill", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      name: "userExchanges",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "users",
      outputs: [
        { internalType: "address", name: "userAddress", type: "address" },
        { internalType: "string", name: "userName", type: "string" },
        { internalType: "uint256", name: "reputation", type: "uint256" },
        { internalType: "uint256", name: "ratingCount", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
  ],
];
